# Generated by Django 2.2.10 on 2020-12-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='Templates',
        ),
    ]
