# Generated by Django 2.2.10 on 2020-12-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201221_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates',
            new_name='TemplateHTML',
        ),
    ]
