# Generated by Django 2.2.10 on 2020-12-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201221_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatehtml',
            options={'verbose_name_plural': 'Templates HTML'},
        ),
    ]
