# Generated by Django 2.2.10 on 2020-12-17 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
