# Generated by Django 2.2.10 on 2020-12-23 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201223_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Order__Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name_plural': 'Order__OrderProducts'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product__Categories'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name_plural': 'Product__SubCategories'},
        ),
        migrations.AlterField(
            model_name='order',
            name='bill_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_address', to='core.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_address', to='core.Address'),
        ),
    ]
