# Generated by Django 2.2.10 on 2020-12-24 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201223_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ('order',), 'verbose_name_plural': 'Order__OrderProducts'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'ordering': ('-order',), 'verbose_name': 'Order__Refund'},
        ),
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
    ]
