# Generated by Django 2.2.10 on 2020-12-24 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201224_0255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Order__Addresses'},
        ),
    ]
