# Generated by Django 2.2.10 on 2020-12-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201224_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
