# Generated by Django 2.2.10 on 2020-12-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201226_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='ProductTopic',
        ),
        migrations.AlterModelOptions(
            name='producttopic',
            options={'verbose_name_plural': 'Product__Topic'},
        ),
        migrations.AlterField(
            model_name='productgroups',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='groups', to='core.Product'),
        ),
    ]
