# Generated by Django 2.2.10 on 2021-01-08 18:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20210107_1842'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'payment')},
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together={('order', 'product')},
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
